---
title: '#SGG Geochem'
author: "André Soares"
date: "30 January 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r set-options, echo=FALSE, cache=FALSE}
options(width = 500)
```

```{r echo=FALSE, fig.height=8, fig.width=18, message=FALSE, warning=FALSE}
# library(ggfortify)
library(cowplot)
library(ggplot2)
library(ggforce)
library(magrittr)
library(ggrepel)
```

```{r fig.height=7, fig.width=7, message=FALSE, warning=FALSE, include=FALSE}
nmds_ps.b.r_colors_by_name = c("Celynen North" = "#440a31",
                               "Crumlin Navigation" = "#aa4455",
                               "Six Bells" = "#ef7ac8",
                               "Blaenavon" = "#08243f",
                               "Cefn Hengoed" = "#4488aa",
                               "Dinas" = "#8cc5ff",
                               "Glyncastle" = "#0c4c2c",
                               "Morlais" = "#03a353",
                               "Mountain Gate" = "#89d6af",
                               "Taff Bargoed" = "#774411",
                               "Ynysarwed" = "#ff9430",
                               "Lindsay" = "#DDAA77",
                               "Taff's Well" = "#cec400")

pca_table_mM=read.csv("SGG_hydro_and_geochemistry_v3_tidy_mM.csv", header=TRUE)
pca_table_mM_noNA = pca_table_mM[ , colSums(is.na(pca_table_mM)) == 0]
pca_table_mM_noNA$NaCa_ratio = (pca_table_mM_noNA$Na/(pca_table_mM_noNA$Na + pca_table_mM_noNA$Ca))
```

```{r echo=FALSE, fig.height=4, fig.width=8, message=FALSE, warning=FALSE}
ggplot(pca_table_mM_noNA, aes(Cl, NaCa_ratio, 
                              size=Temp.C,
                              fill=Site.name,
                              shape=Month)) +
  geom_point(alpha=0.7, colour="black", stroke=.7) +
  geom_vline(xintercept = 0.75, linetype="dashed") +
  geom_hline(yintercept = 0.5, linetype="dashed") +
  scale_x_log10() +
  scale_fill_manual(values=nmds_ps.b.r_colors_by_name) +
  scale_colour_manual(guide=F) +
  scale_shape_manual(values = c(22,21,24)) +
  guides(colour = guide_legend(show=F),
         fill = guide_legend(override.aes = list(size=6,
                                                 shape=21), 
                               nrow = 4, title="Sites",
                               title.position="top", title.hjust = 0.5),
         shape = guide_legend(override.aes = list(size=6), nrow = 3,
                               title.position="top", title.hjust = 0.5),
         size = guide_legend(nrow=4,
                               title.position="top", title.hjust = 0.5)) +
  labs(x=bquote(Cl^'-'~(mM)),
       y=expression(Na^'+'/(Na^'+'+Ca^'2+')~ratio),
       size="Temperature (ºC)",
       color="Site") +
  theme_bw() +
  theme(legend.position = "bottom")

ggsave("sgg_geochem_hor.png", dpi = "retina")
```

```{r, fig.height=4, fig.width=8}
ggplot(pca_table_mM_noNA, aes(Cl, NaCa_ratio,
                              fill = Site.name,
                              shape=Month)) +
  geom_point(alpha=0.7, size = 5,
             colour="black",
             stroke=.7) +
  geom_text_repel(data = pca_table_mM_noNA %>% 
                    dplyr::filter(Month == "April", Time_point == 1,
                           Site.name %in% c("Lindsay","Morlais",
                                         "Crumlin Navigation",
                                         "Dinas",
                                         "Taff's Well")),
                  aes(label=Site.name),
                  nudge_x = -.05,
                  nudge_y = -.03,
                  direction = "y", 
                  fontface = "bold",
                  segment.size  = 0.5,
                  segment.color = "black") +
  geom_text_repel(data = pca_table_mM_noNA %>% 
                    dplyr::filter(Month == "April", Time_point == 1,
                           Site.name %in% c("Ynysarwed",
                                         "Mountain Gate","Blaenavon",
                                         "Celynen North")),
                  aes(label=Site.name),
                  nudge_x = .03,
                  nudge_y = -.01,
                  direction = "y", 
                  fontface = "bold",
                  segment.size  = 0.1,
                  segment.color = "black") +
  geom_text_repel(data = pca_table_mM_noNA %>% 
                    dplyr::filter(Month == "April", Time_point == 1,
                           Site.name == "Taff Bargoed"),
                  aes(label=Site.name),
                  nudge_x = .03,
                  nudge_y = -.04,
                  direction = "y", 
                  fontface = "bold",
                  segment.size  = 0.1,
                  segment.color = "black") +
  geom_text_repel(data = pca_table_mM_noNA %>% 
                    dplyr::filter(Month == "April", Time_point == 1,
                           Site.name == "Cefn Hengoed"),
                  aes(label=Site.name),
                  nudge_x = .08,
                  nudge_y = -.01,
                  direction = "y", 
                  fontface = "bold",
                  segment.size  = 0.3,
                  segment.color = "black") +
  geom_text_repel(data = pca_table_mM_noNA %>% 
                    dplyr::filter(Month == "April", Time_point == 1,
                           Site.name == "Six Bells"),
                  aes(label=Site.name),
                  nudge_x = .04,
                  nudge_y = -.01,
                  direction = "y", 
                  fontface = "bold",
                  segment.size  = 0.3,
                  segment.color = "black") +
  geom_text_repel(data = pca_table_mM_noNA %>% 
                    dplyr::filter(Month == "April", Time_point == 1,
                           Site.name == "Glyncastle"),
                  aes(label=Site.name),
                  nudge_x = .01,
                  nudge_y = -.01,
                  direction = "y", 
                  fontface = "bold",
                  segment.size  = 0.3,
                  segment.color = "black") +
  scale_fill_manual(values = c("#f7f7f7","#cccccc","#969696","#636363","#f7f7f7",
                               "#f7f7f7","#cccccc","#969696","#636363","#252525",
                               "#f7f7f7","#cccccc","#969696"), 
                    guide=F) +
  scale_colour_manual(guide=F) +
  scale_shape_manual(values = c(22,21,24)) +
  guides(shape = guide_legend(override.aes = list(size=6), nrow = 1,
                               title.position="left", title.hjust = 0.5)) +
  labs(x=bquote(Cl^'-'~(mM)),
       y=expression(Na^'+'/(Na^'+'+Ca^'2+')~ratio)) +
  theme_bw() +
  theme(legend.position = "bottom")

ggsave("sgg_geochem_hor.png", dpi = "retina")
```
