---
title: "SGG - How do Taff's Well and TW Pumped compare?"
author: "André Soares"
date: "27 February 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r initial loadings, include=FALSE}
library(dada2); packageVersion("dada2")
library(ggplot2); packageVersion("ggplot2")
library(phyloseq); packageVersion("phyloseq")
library(data.table); packageVersion("data.table")
library(DESeq2); packageVersion("DESeq2")
library(dplyr)
library(plyr)
library(magrittr)
library(RColorBrewer)
library(phangorn)
library(DECIPHER)
library("structSSI")
library(ips)
library(msa)
library(picante)
library(igraph)
library(cowplot)
library(plotly)
library(lemon)
```

```{r load SV data, echo=FALSE}
SGG_SVt = readRDS("/media/andre/B2F8C9A0F8C962E9/SGG_16S_analysis/SGG_16S_data_trimmed_DADA2_table/seqtab_final.rds")
SGG_Tax = readRDS("/media/andre/B2F8C9A0F8C962E9/SGG_16S_analysis/SGG_16S_data_trimmed_DADA2_table/tax_final.rds")
sgg_metadata<-read.csv("/media/andre/B2F8C9A0F8C962E9/SGG_16S_analysis/SGG_16S_metadata/SGG_metadata.csv", header=TRUE)
order<-rownames(SGG_SVt)
sgg_metadata_ord<-sgg_metadata[match(order, sgg_metadata$Sample_Code),]
rownames(sgg_metadata_ord) <- sgg_metadata_ord$Sample_Code
ps <- phyloseq(otu_table(SGG_SVt, taxa_are_rows=FALSE),
               sample_data(sgg_metadata_ord), 
               tax_table(SGG_Tax))
ps.b = subset_samples(ps, Sample_type != "Control")
ps.b <- prune_taxa(taxa_sums(ps.b) > 0, ps.b)
#order months
sample_data(ps.b)$Month = factor(sample_data(ps.b)$Month, 
                                 levels = c("April","August","December"))
#to relative abundances
ps.b = subset_taxa(ps.b, Kingdom %in% c("Archaea", "Bacteria"))
ps.b.r <-  transform_sample_counts(ps.b, function(x) {x/sum(x)} ) 
```

Filtering the dataset to hold only samples from Taff's Well and Taff's Well PUMPED from August.

```{r}
ps.b.r.tf = subset_samples(ps.b.r,
                      Site.name == "Taffs Well PUMPED" | Site.name == "Taffs Well")
ps.b.r.tf = subset_samples(ps.b.r.tf,
                      Month == "August")

ps.b.r.tf.glom <- tax_glom(ps.b.r.tf, taxrank = 'Phylum', NArm = FALSE)
ps.b.r.tf.glom.psdf <- data.table(psmelt(ps.b.r.tf.glom))
ps.b.r.tf.glom.psdf$Phylum <- as.character(ps.b.r.tf.glom.psdf$Phylum)
ps.b.r.tf.glom.psdf[, median := median(Abundance, na.rm = TRUE), 
                 by = "Phylum"]
ps.b.r.tf.glom.psdf[(median <= 0.01), Phylum := "Other"]
ps.b.r.tf.glom.psdf.noProteo<-ps.b.r.tf.glom.psdf[!grepl("Proteobacteria", ps.b.r.tf.glom.psdf$Phylum),]
ps.b.r.tf.ProtCl = subset_taxa(ps.b.r.tf, Phylum == "Proteobacteria")
ps.b.r.tf.ProtCl.glom <- tax_glom(ps.b.r.tf.ProtCl, taxrank = 'Class', NArm = FALSE)
ps.b.r.tf.ProtCl.glom.psdf <- data.table(psmelt(ps.b.r.tf.ProtCl.glom))
ps.b.r.tf.ProtCl.glom.psdf$Class <- as.character(ps.b.r.tf.ProtCl.glom.psdf$Class)
ps.b.r.tf.ProtCl.glom.psdf[, median := median(Abundance, na.rm = TRUE), 
                        by = "Class"]
ps.b.r.tf.ProtCl.glom.psdf[(median <= 0.01), Class := "Other Proteobacteria"]
ps.b.r.tf.ProtCl.glom.psdf.noP <- subset(ps.b.r.tf.ProtCl.glom.psdf, select = -Phylum)
names(ps.b.r.tf.glom.psdf.noProteo)[names(ps.b.r.tf.glom.psdf.noProteo) == 'Phylum'] <- 'Taxa'
names(ps.b.r.tf.ProtCl.glom.psdf.noP)[names(ps.b.r.tf.ProtCl.glom.psdf.noP) == 'Class'] <- 'Taxa'

ps.b.r.tf.ProteoCl.AllPhy <- rbind(ps.b.r.tf.glom.psdf.noProteo, ps.b.r.tf.ProtCl.glom.psdf.noP)
ps.b.r.tf.ProteoCl.AllPhy.plot<-ggplot(ps.b.r.tf.ProteoCl.AllPhy[Abundance > 0], 
                                    aes(x = Site.name, y = Abundance/3, fill = Taxa)) + 
  geom_bar(stat = "identity", width = 0.4) +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 25, hjust = 1, size = 10),
        axis.text.y = element_text(size = 10)) + 
  guides(fill = guide_legend(keywidth = 1, keyheight = 1)) +
  scale_y_continuous(expand = c(0,0)) +
  ylab("Relative Abundance\n")
```
```{r}
ps.b.r.tf.ProteoCl.AllPhy.plot
```

Looks like they're pretty much the same!

Not really looking much further into it.